### ISSUE TITLE
HDFView 3.3.0 crashes on a HDF4 file

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdfview#120]
The test file is available from #119.

See https://youtu.be/vMuke2l4eP8 to reproduce.

**Comment by byrnHDF** [comment]
Might be an object library HDF4 datatype error.
Not specific to a Mac.

**Comment by hyoklee** [comment]
@byrnHDF did you open a new issue in HDF4 before you close this?

**Comment by byrnHDF** [comment]
See https://github.com/HDFGroup/hdf4 issue #355
