### ISSUE TITLE
Update a few icons used in HDFView

### ISSUE THREAD

**Issue by jhendersonHDF** [HDFGroup/hdfview#121]
The following icons should be updated with transparency:

https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/apps.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/audio.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/datasetA.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/datatype.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/datatypeA.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/foldercloseA.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/folderopenA.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdf4.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdf4R.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdf5.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdf5R.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdfnc.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdfnc3.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdfnc3R.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/hdfncR.gif
https://github.com/HDFGroup/hdfview/blob/master/src/org.hdfgroup.hdfview/hdf/view/icons/imageA.gif

**Comment by byrnHDF** [comment]
Updated icons.
