### ISSUE TITLE
Incorrect Version Number

### ISSUE THREAD

**Issue by sanssecours** [HDFGroup/hdfview#122]
# Description

The macOS version of HDFView (3.3.0) contains the wrong version number: `99.99.99` instead of `3.3.0`

# Steps to Reproduce

1. Download `HDFView-3.3.0-macos11_64.tar.gz` from [here](https://www.hdfgroup.org/downloads/hdfview/)
2. Open the downloaded archive file
3. Open the disk image `HDFView-3.3.0.dmg`
4. Press “Agree”
5. Select the HDFView application in Finder
6. Open the info dialog: <kbd>⌘</kbd> + <kbd>I</kbd>

# Expected Result

The info dialog should show the version string: `3.3.0`

# Actual Result

The info dialog shows the version string `99.99.99`

<img width="385" alt="HDFView Version" src="https://user-images.githubusercontent.com/691989/233832011-c582be47-dbdf-4480-af11-4c9dc9ac0c92.png">

# General Information

OS: macOS `13.3.1`
HDFView Version: `3.3.0`

**Comment by byrnHDF** [comment]
The macosx/Info.plist had not been updated correctly.

**Comment by byrnHDF** [comment]
hdfview-3-1.14 dev branch updated.
