### ISSUE TITLE
Datasets with datatype float16 cannot be displayed in HDFView

### ISSUE THREAD

**Issue by nikolasborrel** [HDFGroup/hdfview#138]
When writing datasets with datatype float16, HDFView 3.3.0 returns the error "data value is null." 

Is there a solution for this?

![Screenshot 2023-06-26 at 13 24 44](https://github.com/HDFGroup/hdfview/assets/9203478/0b3cb698-66be-46f3-8ad3-81ca1735c3d2)

**Comment by nikolasborrel** [comment]
I'm using HDFView on MacOS, in case.

**Comment by byrnHDF** [comment]
There should be a way to display a custom float datatype, we will need a testfile at the least. A "C" generate file program would be helpful. 
Does h5dump display this correctly?

**Comment by sanssecours** [comment]
I think I have the same problem. As fars as I can tell the datatype does not matter. I uploaded an example file: [1695739243.hdf5.zip](https://github.com/HDFGroup/hdfview/files/12729119/1695739243.hdf5.zip)

Here is a screenshot of the data set `acceleration` of the example file in HDFView 3.2.0:

<img width="374" alt="HDFView 3 2 0" src="https://github.com/HDFGroup/hdfview/assets/691989/fb720574-f99d-4de7-9009-e9b685211850">

The same data in HDFView 3.3.1:

<img width="366" alt="HDFView 3 3 1" src="https://github.com/HDFGroup/hdfview/assets/691989/b00ea600-9ac7-443e-8d65-fe88011375d5">

> Does h5dump display this correctly?

Yep.  The command:

```sh
h5dump -d acceleration measurement/1695739243.hdf5 | head -n 50
```

prints the following output on my machine:

```
HDF5 "measurement/1695739243.hdf5" {
DATASET "acceleration" {
   DATATYPE  H5T_COMPOUND {
      H5T_STD_U8LE "counter";
      H5T_STD_U64LE "timestamp";
      H5T_IEEE_F32LE "x";
   }
   DATASPACE  SIMPLE { ( 14736 ) / ( H5S_UNLIMITED ) }
   DATA {
   (0): {
         1,
         0,
         -0.587472
      },
   (1): {
         1,
         0,
         -0.563058
      },
   (2): {
         1,
         0,
         -0.572213
      },
   (3): {
         2,
         179,
         -0.529488
      },
   (4): {
         2,
         179,
         -0.560006
      },
   (5): {
         2,
         179,
         -0.596628
      },
   (6): {
         3,
         364,
         -0.541695
      },
   (7): {
         3,
         364,
         -0.53254
      },
   (8): {
```

**Comment by byrnHDF** [comment]
A simple compound should display! I will double-check but I don't see a reason right now. I will try that file, too. Are these problems on a mac only?

**Comment by byrnHDF** [comment]
I think this must be a mac specific issue. linux is fine.

**Comment by byrnHDF** [comment]
I would like to request more info on system, os version in particular.

**Comment by sanssecours** [comment]
> I would like to request more info on system, os version in particular.

I use macOS, just like the original author of the issue. 

> I think this must be a mac specific issue. linux is fine.

That might be correct.

**Comment by byrnHDF** [comment]
Do you have a version number for the MacOS?

**Comment by sanssecours** [comment]
> Do you have a version number for the MacOS?

macOS `13.6` (22G120)

**Comment by byrnHDF** [comment]
Thanks

**Comment by byrnHDF** [comment]
I also found that file failed on windows. Then I noticed that the dataset is compressed! And trying a non-compressed file of compounds works. 
[tcompound_complex2.zip](https://github.com/HDFGroup/hdfview/files/12730689/tcompound_complex2.zip)

**Comment by byrnHDF** [comment]
AHHHH!  The first build of 3.3.1on Sep 5 used incomplete HDF5 binaries (without compression). We released new 1.14.2 binaries and rebuilt HDFView on Sep 22. Please redownload the newer HDFView.

**Comment by sanssecours** [comment]
Looks like both the “Installer” and the “Application Image” for macOS from the offical [download page](https://www.hdfgroup.org/downloads/hdfview) are still outdated. Both versions show `*ERROR*` fields instead of the stored data. As far as I can tell from the modification/creation dates, the “Installer“ application was built on the 23th of August while the “Application Image” app was built a day later (24th of August).

For anyone else searching for the **updated and working binaries**, they are available **[here]( https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.3.1/bin/)**.

**Comment by byrnHDF** [comment]
Looks like we dropped the ball on updating the download site. The files should be there tomorrow (should happen soon)

**Comment by theGidy** [comment]
Please update your download links on https://www.hdfgroup.org/downloads/hdfview/  as well, i had to use this link https://support.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/hdfview-3.3.1/bin/ to recive the new correct version.

**Comment by byrnHDF** [comment]
Releases from now on are available from [github](https://github.com/HDFGroup/hdfview/releases)
