### ISSUE TITLE
HDFView 3.3.0 shows incorrect references in compound types in datasets

### ISSUE THREAD

**Issue by rly** [HDFGroup/hdfview#147]
I have an HDF5 file with a dataset with a compound dtype consisting of `(int, int, object reference to a group)`. Displaying this data in HDFView is incorrect. All the object references are to the same first group.

Here is a zip file with an example single 182 KB .h5 file [test_tsref.h5.zip](https://github.com/HDFGroup/hdfview/files/12187572/test_tsref.h5.zip) (GitHub does not allow uploading files with h5 extensions, so I zipped it. Happy to share it elsewhere if that is preferred)

The dataset is at `/acquisition/test_dynamic_table/test_timeseries_reference_vector_data`
<img width="1066" alt="image" src="https://github.com/HDFGroup/hdfview/assets/310197/8cc4f002-679c-4df6-b8c0-d7775e011f8a">
The two rows should have different object references: `/acquisition/test_timeseries1` and `/acquisition/test_timeseries2`.

**Comment by byrnHDF** [comment]
references in compound container types has had many issues, this looks like it may be another. I will debug and locate the problem to see if there it is an issue in the object library or in the JNI interface of hdf5.

**Comment by byrnHDF** [comment]
This turned out to be real simple, just needed to use the supplied index in the arraycopy for object refs.

**Comment by byrnHDF** [comment]
Fixed in 3.3.1 release

**Comment by rly** [comment]
Thanks!
