### ISSUE TITLE
I open a file but not displayed elements and I don't get any errors.

### ISSUE THREAD

**Issue by manuel-masiello** [HDFGroup/hdfview#172]
Good morning.

I don't understand why but the tool does not display elements of my hdf5 file. The tool is just empty as if the file was empty.

For your information, I generated the HDF5 file myself with Python and I can open it and read the data in a notebook without error.

I work under Linux (Ubuntu)

Info:
```

HDFView root - /home/*******
User property file - /home/*******/.hdfview2.11
```

Metadata:

```
/ (0)
    Group size = 0
    Number of attributes = 0
```

![Capture d’écran du 2024-01-24 11-49-23](https://github.com/HDFGroup/hdfview/assets/14220699/45605169-df0a-413b-bf11-c39836728809)

**Comment by manuel-masiello** [comment]
I just opened the same file in Panoly and it works perfectly :

![Capture d’écran du 2024-01-24 12-01-17](https://github.com/HDFGroup/hdfview/assets/14220699/2321fbb1-5504-4541-a96e-5261d6e6ea82)

**Comment by bmribler** [comment]
Latest version of HDFView is available [here](https://portal.hdfgroup.org/downloads/hdfview/hdfview3_3_1.html).

**Comment by manuel-masiello** [comment]
Good morning. Thank you for your reply. 

Indeed, version 3.3.1 works. This is the default version of Ubuntu that does not work. 

Thank you for your work.
