### ISSUE TITLE
Attributes with variable length not working

### ISSUE THREAD

**Issue by Dr-Electron** [HDFGroup/hdfview#36]
If I try to create an image dataset with Python, it doesn't work if I use the default dtype. I need to create my own string type with a set length.

Python code to reproduce:
```python 
import h5py

file = h5py.File('dset_not_working.h5','w')
dataset = file.create_dataset("dset",(4, 6), h5py.h5t.STD_I32BE)

dataset.attrs.create('CLASS', 'IMAGE')
dataset.attrs.create('IMAGE_VERSION', '1.2')
dataset.attrs.create('IMAGE_SUBCLASS', 'IMAGE_GRAYSCALE')

file.close()

file = h5py.File('dset_working.h5','w')
dataset = file.create_dataset("dset",(4, 6), h5py.h5t.STD_I32BE)

value = "IMAGE"
dt = h5py.string_dtype(length=len(value))
dataset.attrs.create('CLASS', value, dtype=dt)
value = '1.2'
dt = h5py.string_dtype(length=len(value))
dataset.attrs.create('IMAGE_VERSION', value, dtype=dt)
value = 'IMAGE_GRAYSCALE'
dt = h5py.string_dtype(length=len(value))
dataset.attrs.create('IMAGE_SUBCLASS', value, dtype=dt)

file.close()
```

**Comment by byrnHDF** [comment]
This issue should be filed on h5py issues

**Comment by Dr-Electron** [comment]
But to me, it seems a viewer issue. I tested with both the C lib and the python lib. In both cases, if I use variable length, the viewer doesn't recognize the attributes

**Comment by byrnHDF** [comment]
Oh, that was not clear. Have you tried to use the h5dump tool as well?
Also, if h5dump has the same problem, you could open an issue with the helpdesk.

**Comment by Dr-Electron** [comment]
Sorry, but maybe I still didn't explain it well enough. h5dump gives the same output for both files, except the `STRSIZE` of course. So the file gets written correctly. But in one file the viewer recognizes the dataset correctly as type image and in the other it doesn't and just shows the file as normal dataset.

**Comment by byrnHDF** [comment]
To have hdfview recognize a dataset as an image it must follow the spec: https://support.hdfgroup.org/HDF5/doc/ADGuide/ImageSpec.html

**Comment by Dr-Electron** [comment]
Got it, thanks. Didn't see that the spec explicitly mention a size.

**Comment by byrnHDF** [comment]
I am still looking in the code to find the exact checks, but figure the spec would be best until I do find the code block.

**Comment by byrnHDF** [comment]
> I am still looking in the code to find the exact checks, but figure the spec would be best until I do find the code block.

hdf/object/h5/H5File.java  about line 675 - createImageAttributes

it has bit of comments concerning images.
