### ISSUE TITLE
Check aarch64 in machine.arch property

### ISSUE THREAD

**Issue by jiegec** [HDFGroup/hdfview#73]
In the build.xml https://github.com/HDFGroup/hdfview/blob/854748012ceb50fb021200aa274363ef33a4b3c6/build.xml#L152-L157

It only handles two arch: x86_64 and ppc64le. I am building HDFView on aarch64, and it collected the wrong x86_64 native jars for swt.

I have to override the property in command line:

```shell
ant -Dmachine.arch=aarch64
```

**Comment by byrnHDF** [comment]
Switching to the following might work:
    <condition property="machine.arch" value="aarch64">
        <matches pattern="aarch64" string="${os.arch}" />
    </condition>
    <condition property="machine.arch" value="ppc64le">
        <matches pattern="ppc64le" string="${os.arch}" />
    </condition>
    <condition property="machine.arch" value="x86_64">
        <matches pattern="x86_64" string="${os.arch}" />
    </condition>
    <condition property="machine.arch" value="unknown">
        <not>  
           <isset property="machine.arch"/>
        </not>
    </condition>

**Comment by byrnHDF** [comment]
Fixed in next release.
