### ISSUE TITLE
two projects

### ISSUE THREAD

**Issue by untereiner** [HDFGroup/hdfview#95]
Hello,
Would it be possible to separate the `object` project that handles the files and the `hdfview` project into two separate projects with separate repositories ?
I would only need the hdf5 file handling part in project.

**Comment by byrnHDF** [comment]
That is not in our plans as the object library is designed for use by HDFView.

**Comment by untereiner** [comment]
@byrnHDF I understand by what if another project would use on the object library without the GUI ?

**Comment by byrnHDF** [comment]
The object library could be used as we strive to keep an GUI code out of the library, but it was designed to provide a unified interface between hdf4/5 and the GUI. So it has made a number of compromises.

________________________________________
